### ISSUE TITLE
https://dash.adoptium.net/trends cannot be visited in a new tab

### ISSUE THREAD

**Issue by jiekang** [adoptium/dash.adoptium.net#272]
If you open a new tab and visit https://dash.adoptium.net/trends

it results in a Page Not Found view.

If you visit https://dash.adoptium.net/ first and click trends, it works. I believe this is a regression as I have old documents with the /trends link.

**Comment by netomi** [comment]
To be clear, the proposed solution avoids the problem by using hash history instead of browser history. This would support bookmarking any navigation within the single-page app. If you need to support the existing urls (like /trends) you will need to add redirect directives for netlify afaict.

**Comment by xavierfacq** [comment]
Can you assign this issue to me, i'll take a look at this.

**Comment by jiekang** [comment]
Thank you for fixing this @xavierfacq!
