### ISSUE TITLE
Chart labels are unreadable

### ISSUE THREAD

**Issue by tellison** [adoptium/dash.adoptium.net#348]
The chart labels quickly become unreadable when drilling down on download numbers, this makes the chart unusable.

To recreate:
 - go to dash.adoptium.net and select the downloads tab
 - click on a column of the Github downloads bar chart to drill down to releases
 - click on a column of the releases bar chart to see a specific release
 - notice that there are stats for all release packages, and that they have long names, making them indistinguishable and unusable
 
![Screenshot 2023-09-19 at 10 02 45](https://github.com/adoptium/dash.adoptium.net/assets/621161/052d71f0-7150-45cc-84a8-c5ac268d0b9f)

This will require some thought and redesign about how to depict these numbers in a friendlier format. They can't all appear on one chart, and some packages are less interesting than others.

**Comment by smlambert** [comment]
This is because we are using highcharts without modifying its default configuration.  It is highly configurable.

**Comment by gdams** [comment]
We probably just want to write util function that parses the filenames and turns them into useful labels

**Comment by tellison** [comment]
Or maybe split that single barchart into more than one separate chart.
For example, create a separate chart for
 - JDKs & JREs 
 - debug & test images 
 - source & SBOMs

or some other meaningful grouping, rather than putting them all together

**Comment by xavierfacq** [comment]
What do you think if we add a new level, by "Arch" ?  (Note that it can be by OS instead)


![image](https://github.com/adoptium/dash.adoptium.net/assets/3774556/499a971c-a6be-4733-9159-6df9cfb0b67f)

![image](https://github.com/adoptium/dash.adoptium.net/assets/3774556/1f20339a-38ec-441c-b260-61f81daf8bbb)
