### ISSUE TITLE
Docker pulls bar chart is not useful

### ISSUE THREAD

**Issue by tellison** [adoptium/dash.adoptium.net#349]
The "Docker Pulls" bar chart at the bottom of the dash downloads page is no longer useful. It was interesting when we had a variety of docker image groups to show, but now there is only "eclipse-temurin" so a chart is not helpful. The absolute number is already shown in the "Total Downloads" chart on the same page.

**Comment by xavierfacq** [comment]
Ok, I remove the  section, OK?
