### ISSUE TITLE
Dashboard shows incorrect download numbers

### ISSUE THREAD

**Issue by tellison** [adoptium/dash.adoptium.net#385]
The dashboard bar chart shows the JDK downloads at
https://dash.adoptium.net/download

![Screenshot 2023-10-17 at 14 40 33](https://github.com/adoptium/adoptium.net/assets/621161/4b4e9c63-2e4c-4b36-882d-e117f5b2d001)

At this level the column for all JDK21 releases is currently showing 795k…, but when I click on that column it shows only one JDK21 release, as expected, but with a total of 111k

![Screenshot 2023-10-17 at 14 43 17](https://github.com/adoptium/adoptium.net/assets/621161/b9964159-7276-4981-85dd-1e39f7fa183d)

The roll-up into JDK versions be the total of all releases of that version

**Comment by xavierfacq** [comment]
Here are results of my first investigations, let's focus on JDK21 that has smaller values.
IMHO there is an inconsistency of the data returned by the API.
I can "fix" the display by computing sums based on the last call (all elements), but I think we must find why this wrong values are returned.

:warning:  This call https://api.adoptium.net/v3/stats/downloads/total/ returns **795231** for the version 21:

`{
    "date": "2023-10-17T13:53:43Z",
    "docker_pulls": {
        "eclipse-temurin": 76264622
    },
    "github_downloads": {
        "8": 41425474,
        "11": 50446738,
        "16": 6045907,
        "17": 47679337,
        "18": 10219922,
        "19": 7770668,
        "20": 3745056,
        "21": 795231,
        "22": 25476
    },
    "total_downloads": {
        "docker_pulls": 76264622,
        "github_downloads": 168153809,
        "total": 244418431
    }
}`

:warning:  This call https://api.adoptium.net/v3/stats/downloads/total/21 returns **111574**
`{
    "jdk-21+35": 111574
}`

:heavy_check_mark:  This call https://api.adoptium.net/v3/stats/downloads/total/21/jdk-21+35 returns a sum of **174428**
`{
    "OpenJDK21U-jdk-sources_21_35.tar.gz": 235,
    "OpenJDK21U-jre_x64_linux_hotspot_21_35.tar.gz": 1748,
    "OpenJDK21U-debugimage_x64_linux_hotspot_21_35.tar.gz": 20,
    "OpenJDK21U-sbom_x64_linux_hotspot_21_35.json": 4,
    "OpenJDK21U-testimage_x64_linux_hotspot_21_35.tar.gz": 3,
    "OpenJDK21U-static-libs-glibc_x64_linux_hotspot_21_35.tar.gz": 27,
    "OpenJDK21U-jdk_x64_linux_hotspot_21_35.tar.gz": 22020,
    "OpenJDK21U-static-libs-glibc_aarch64_linux_hotspot_21_35.tar.gz": 26,
    "OpenJDK21U-debugimage_aarch64_linux_hotspot_21_35.tar.gz": 21,
    "OpenJDK21U-jdk_aarch64_linux_hotspot_21_35.tar.gz": 1084,
    "OpenJDK21U-jre_aarch64_linux_hotspot_21_35.tar.gz": 486,
    "OpenJDK21U-testimage_aarch64_linux_hotspot_21_35.tar.gz": 6,
    "OpenJDK21U-sbom_aarch64_linux_hotspot_21_35.json": 5,
    "OpenJDK21U-static-libs-musl_x64_alpine-linux_hotspot_21_35.tar.gz": 9,
    "OpenJDK21U-testimage_x64_alpine-linux_hotspot_21_35.tar.gz": 2,
    "OpenJDK21U-sbom_x64_alpine-linux_hotspot_21_35.json": 5,
    "OpenJDK21U-jdk_x64_alpine-linux_hotspot_21_35.tar.gz": 930,
    "OpenJDK21U-jre_x64_alpine-linux_hotspot_21_35.tar.gz": 323,
    "OpenJDK21U-debugimage_x64_alpine-linux_hotspot_21_35.tar.gz": 21,
    "OpenJDK21U-static-libs_x64_mac_hotspot_21_35.tar.gz": 8,
    "OpenJDK21U-debugimage_x64_mac_hotspot_21_35.tar.gz": 4,
    "OpenJDK21U-sbom_x64_mac_hotspot_21_35.json": 3,
    "OpenJDK21U-jdk_x64_mac_hotspot_21_35.tar.gz": 7887,
    "OpenJDK21U-jdk_x64_mac_hotspot_21_35.pkg": 5816,
    "OpenJDK21U-jre_x64_mac_hotspot_21_35.tar.gz": 878,
    "OpenJDK21U-jre_x64_mac_hotspot_21_35.pkg": 715,
    "OpenJDK21U-testimage_x64_mac_hotspot_21_35.tar.gz": 6,
    "OpenJDK21U-debugimage_x64_windows_hotspot_21_35.zip": 30,
    "OpenJDK21U-jdk_x64_windows_hotspot_21_35.zip": 55477,
    "OpenJDK21U-jdk_x64_windows_hotspot_21_35.msi": 39445,
    "OpenJDK21U-testimage_x64_windows_hotspot_21_35.zip": 8,
    "OpenJDK21U-jre_x64_windows_hotspot_21_35.zip": 9090,
    "OpenJDK21U-jre_x64_windows_hotspot_21_35.msi": 7726,
    "OpenJDK21U-static-libs_x64_windows_hotspot_21_35.zip": 20,
    "OpenJDK21U-sbom_x64_windows_hotspot_21_35.json": 3,
    "OpenJDK21U-testimage_aarch64_alpine-linux_hotspot_21_35.tar.gz": 3,
    "OpenJDK21U-static-libs-musl_aarch64_alpine-linux_hotspot_21_35.tar.gz": 8,
    "OpenJDK21U-jre_aarch64_alpine-linux_hotspot_21_35.tar.gz": 85,
    "OpenJDK21U-sbom_aarch64_alpine-linux_hotspot_21_35.json": 2,
    "OpenJDK21U-jdk_aarch64_alpine-linux_hotspot_21_35.tar.gz": 186,
    "OpenJDK21U-debugimage_aarch64_alpine-linux_hotspot_21_35.tar.gz": 57,
    "OpenJDK21U-static-libs_aarch64_mac_hotspot_21_35.tar.gz": 5,
    "OpenJDK21U-testimage_aarch64_mac_hotspot_21_35.tar.gz": 2,
    "OpenJDK21U-sbom_aarch64_mac_hotspot_21_35.json": 2,
    "OpenJDK21U-jre_aarch64_mac_hotspot_21_35.tar.gz": 689,
    "OpenJDK21U-jre_aarch64_mac_hotspot_21_35.pkg": 513,
    "OpenJDK21U-jdk_aarch64_mac_hotspot_21_35.tar.gz": 10135,
    "OpenJDK21U-jdk_aarch64_mac_hotspot_21_35.pkg": 8639,
    "OpenJDK21U-debugimage_aarch64_mac_hotspot_21_35.tar.gz": 11
}`


Here are values we should have instead:

![image](https://github.com/adoptium/dash.adoptium.net/assets/3774556/6190f52b-1ce7-4254-896c-612f32e61d35)
